fixtures:
  repositories:
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    puppet: "git://github.com/nesi/puppet-puppet.git"
    apache: "git://github.com/puppetlabs/puppetlabs-apache.git"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
  symlinks:
    puppetdashboard: "#{source_dir}"
