fixtures:
  forge_modules:
    stdlib:
      repo: 'puppetlabs-stdlib'
      ref:  '4.3.2'
    apache:
      repo: 'puppetlabs-apache'
      ref:  '1.1.1'
    vcsrepo:
      repo: 'puppetlabs-vcsrepo'
      ref:  '1.1.0'
    postgresql:
      repo: 'puppetlabs-postgresql'
      ref:  '3.4.2'
    concat:
      repo: 'puppetlabs-concat'
      ref:  '1.1.1'
    ruby:
      repo: 'puppetlabs-ruby'
      ref:  '0.3.0'
    mysql:
      repo: 'puppetlabs-mysql'
      ref:  '2.3.1'
    puppet:
      repo: 'Aethylred-puppet'
      ref:  '1.4.1'
  repositories:
    # none
  symlinks:
    puppetdashboard: "#{source_dir}"
