fixtures:
  repositories:
    stdlib:   
      repo:   'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:    '4.2.1'
    puppet:   
      repo:   'git://github.com/nesi/puppet-puppet.git'
      ref:    '0.2.5'
    apache:   
      repo:   'git://github.com/puppetlabs/puppetlabs-apache.git'
      ref:    '1.0.1'
    concat:   
      repo:   'git://github.com/puppetlabs/puppetlabs-concat.git'
      ref:    '1.1.0'
    vcsrepo:  
      repo:   'git://github.com/puppetlabs/puppetlabs-vcsrepo.git'
      ref:    '0.2.0'
    mysql:  
      repo:   'git://github.com/puppetlabs/puppetlabs-mysql.git'
      ref:    '2.2.3'
  symlinks:
    puppetdashboard: "#{source_dir}"
